### ISSUE TITLE
2 issues in 1 post..

### ISSUE THREAD

**Issue by thekio1984** [Thomz07/Cenamo#1]
1st is that when in LPM & is plugged in to charge, the dock remains yellow when should go green (using tweak defaults/just intstalled without changing anything), but when LPM is off, all works great.

2nd, default yellow you use for LPM, is the wrong yellow compared too apples stock lpm colour, i know we can edit the colours, but yeah, took me a little while to get it about right.

**Comment by Thomz07** [comment]
LPM overrides everything because i made it work as apple do it for their UIBatteryView
Yeah the colors are not the same at all as the original battery. The origonal colors looks too bright on the Dock imo
